"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TrHead = exports.Tr = exports.Td = exports.Th = exports.TableContainer = void 0;
var styled_components_1 = __importDefault(require("styled-components"));
var foundation_1 = require("../../foundation");
exports.TableContainer = styled_components_1.default.table(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  /* enable scroll on small width */\n  display: block;\n  overflow: auto;\n  border-collapse: collapse;\n\n  /* width */\n  ::-webkit-scrollbar {\n    height: 12px;\n  }\n\n  /* Track */\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 10px;\n    background: ", ";\n  }\n\n  /* Handle */\n  ::-webkit-scrollbar-thumb {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.2);\n    border-radius: 10px;\n    background: ", ";\n  }\n\n  /* Handle on hover */\n  ::-webkit-scrollbar-thumb:hover {\n    cursor: pointer;\n    background: ", ";\n  }\n"], ["\n  /* enable scroll on small width */\n  display: block;\n  overflow: auto;\n  border-collapse: collapse;\n\n  /* width */\n  ::-webkit-scrollbar {\n    height: 12px;\n  }\n\n  /* Track */\n  ::-webkit-scrollbar-track {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);\n    border-radius: 10px;\n    background: ", ";\n  }\n\n  /* Handle */\n  ::-webkit-scrollbar-thumb {\n    box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.2);\n    border-radius: 10px;\n    background: ", ";\n  }\n\n  /* Handle on hover */\n  ::-webkit-scrollbar-thumb:hover {\n    cursor: pointer;\n    background: ", ";\n  }\n"])), foundation_1.Color.white, foundation_1.Color.lavender, foundation_1.Color.gainsboro);
exports.Th = styled_components_1.default.th(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  font-family: ", ";\n  font-weight: ", ";\n  line-height: 1.29;\n\n  height: 100px;\n  min-width: 142px;\n  padding: 0px 27px;\n  background-color: ", ";\n  border-bottom: 1px solid rgba(230, 230, 250, 0.7);\n\n  font-size: 0.9rem;\n  text-align: right;\n\n  &:nth-of-type(1) {\n    font-size: 1.125rem;\n    text-align: left;\n\n    /* make first column header sticky */\n    left: 0;\n    position: sticky;\n  }\n\n  ", " {\n    &:nth-of-type(1) {\n      box-shadow: 6px 0px 25px 0px ", ";\n    }\n  }\n"], ["\n  font-family: ", ";\n  font-weight: ", ";\n  line-height: 1.29;\n\n  height: 100px;\n  min-width: 142px;\n  padding: 0px 27px;\n  background-color: ", ";\n  border-bottom: 1px solid rgba(230, 230, 250, 0.7);\n\n  font-size: 0.9rem;\n  text-align: right;\n\n  &:nth-of-type(1) {\n    font-size: 1.125rem;\n    text-align: left;\n\n    /* make first column header sticky */\n    left: 0;\n    position: sticky;\n  }\n\n  ", " {\n    &:nth-of-type(1) {\n      box-shadow: 6px 0px 25px 0px ", ";\n    }\n  }\n"])), foundation_1.Theme.font.sansSerif, foundation_1.Theme.fontWeight.bold, foundation_1.Color.whiteSmoke, foundation_1.MediaQuery.maxWidth.tablet, foundation_1.Color.lavender);
exports.Td = styled_components_1.default.td(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  font-family: ", ";\n  padding: 20px 27px;\n\n  font-weight: ", ";\n  text-align: right;\n\n  &:nth-of-type(1) {\n    font-weight: ", ";\n    text-align: left;\n\n    /* make first column body sticky */\n    left: 0;\n    position: sticky;\n  }\n\n  ", " {\n    &:nth-of-type(1) {\n      box-shadow: 6px 0px 25px 0px ", ";\n      clip-path: inset(0px -30px 0px 0px);\n    }\n  }\n"], ["\n  font-family: ", ";\n  padding: 20px 27px;\n\n  font-weight: ", ";\n  text-align: right;\n\n  &:nth-of-type(1) {\n    font-weight: ", ";\n    text-align: left;\n\n    /* make first column body sticky */\n    left: 0;\n    position: sticky;\n  }\n\n  ", " {\n    &:nth-of-type(1) {\n      box-shadow: 6px 0px 25px 0px ", ";\n      clip-path: inset(0px -30px 0px 0px);\n    }\n  }\n"])), foundation_1.Theme.font.sansSerif, foundation_1.Theme.fontWeight.regular, foundation_1.Theme.fontWeight.bold, foundation_1.MediaQuery.maxWidth.tablet, foundation_1.Color.lavender);
exports.Tr = styled_components_1.default.tr(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  &:nth-of-type(odd) td {\n    background-color: ", ";\n  }\n\n  &:nth-of-type(even) td {\n    background-color: ", ";\n  }\n"], ["\n  &:nth-of-type(odd) td {\n    background-color: ", ";\n  }\n\n  &:nth-of-type(even) td {\n    background-color: ", ";\n  }\n"])), foundation_1.Color.ghostWhite, foundation_1.Color.whiteSmoke);
exports.TrHead = styled_components_1.default.tr(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  padding: 0px 27px;\n"], ["\n  padding: 0px 27px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
