export const letterSpacing = {
  display: {
    mobileSmall: "-1.4px",
    mobile: "-1.5px",
    tablet: "-2px",
    desktop: "-2.33px",
    desktopLarge: "-3.4px",
  },
  h1: {
    mobileSmall: "-1.4px",
    mobile: "-1.5px",
    tablet: "-1.5px",
    desktop: "-2.2px",
    desktopLarge: "-3.5px",
  },
  h2: {
    mobileSmall: "-0.7px",
    mobile: "-0.75px",
    tablet: "-0.9px",
    desktop: "-1.13px",
    desktopLarge: "-1.45px",
  },
  h3: {
    mobileSmall: "-0.45px",
    mobile: "-0.5px",
    tablet: "-0.4px",
    desktop: "-0.6px",
    desktopLarge: "-1px",
  },
  h4: {
    mobileSmall: "-0.45px",
    mobile: "-0.4px",
    tablet: "-0.4px",
    desktop: "-0.5px",
    desktopLarge: "-0.6px",
  },
  h5: {
    mobileSmall: "-0.35px",
    mobile: "-0.4px",
    tablet: "-0.3px",
    desktop: "-0.4px",
    desktopLarge: "-0.5px",
  },
  h6: {
    mobileSmall: "-0.25px",
    mobile: "-0.3px",
    tablet: "-0.3px",
    desktop: "-0.3px",
    desktopLarge: "-0.4px",
  },
  p: {
    mobileSmall: "0px",
    mobile: "0px",
    tablet: "0px",
    desktop: "0px",
    desktopLarge: "0.2px",
  },
  caption: {
    mobileSmall: "0px",
    mobile: "0px",
    tablet: "0px",
    desktop: "0px",
    desktopLarge: "0px",
  },
  label: {
    mobileSmall: "1.1px",
    mobile: "1.2px",
    tablet: "1.2px",
    desktop: "1.8px",
    desktopLarge: "1.8px",
  },
};
