// mjs: https://github.com/webpack/webpack/issues/1403#issuecomment-799346606
import { VanillaExtractPlugin } from "@vanilla-extract/webpack-plugin";
import HtmlWebpackPlugin from "html-webpack-plugin";
import MiniCssExtractPlugin from "mini-css-extract-plugin";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

// https://stackoverflow.com/a/50052194/7435656
const __dirnameCustom = dirname(fileURLToPath(import.meta.url));

export const baseConfig = {
  entry: "./app/index.tsx",

  module: {
    rules: [
      // https://vanilla-extract.style/documentation/integrations/webpack/
      {
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: "css-loader",
            options: {
              url: false, // Required as image imports should be handled via JS/TS import statements
            },
          },
        ],
      },

      // https://webpack.js.org/guides/asset-management/
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"],
        // exclude vanilla extract files:
        // https://github.com/webpack-contrib/css-loader/issues/672#issuecomment-362480828
        exclude: /\.vanilla\.css$/i,
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: "asset/resource",
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: "asset/resource",
      },

      // https://webpack.js.org/guides/typescript/
      {
        /*
         * Note: This rule is referenced in .storybook/main.js
         * If you change this, change it there too.
         */
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },

  // https://webpack.js.org/guides/output-management/
  output: {
    filename: "[name].bundle.js",
    path: resolve(__dirnameCustom, "../build"),
    clean: true,
    hashFunction: "xxhash64", // https://stackoverflow.com/a/73465262/7435656
  },

  resolve: {
    extensions: [".tsx", ".ts", ".js", ".html"],
    extensionAlias: {
      ".js": [".tsx", ".ts", ".js"],
    },
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: "./app/index.html",
    }),
    new VanillaExtractPlugin(),
    new MiniCssExtractPlugin(),
  ],
};
