"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Color = void 0;
var Color;
(function (Color) {
    Color["white"] = "#FFFFFF";
    Color["ghostWhite"] = "#F8F8FF";
    Color["whiteSmoke"] = "#F5F5F5";
    Color["ivory"] = "#FFFFF0";
    Color["floralWhite"] = "#FFFAF0";
    Color["honeyDew"] = "#F0FFF0";
    Color["azure"] = "#F0FFFF";
    Color["lightCyan"] = "#E0FFFF";
    Color["lavender"] = "#E6E6FA";
    Color["gainsboro"] = "#DCDCDC";
    Color["silver"] = "#C0C0C0";
    Color["midnightBlue"] = "#191970";
    Color["royalBlue"] = "#275EFE";
    Color["black"] = "#2F3545";
})(Color = exports.Color || (exports.Color = {}));
