import { Story, Meta } from "@storybook/react";
import { TypographyProps } from "../Typography";
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Display: Story<TypographyProps>;
export declare const Heading1: Story<TypographyProps>;
export declare const Heading2: Story<TypographyProps>;
export declare const Heading3: Story<TypographyProps>;
export declare const Heading4: Story<TypographyProps>;
export declare const Heading5: Story<TypographyProps>;
export declare const Heading6: Story<TypographyProps>;
export declare const Paragraph: Story<TypographyProps>;
export declare const Caption: Story<TypographyProps>;
export declare const Label: Story<TypographyProps>;
